datadog_demo:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: datadog
      password: datadog
      dbname: datadog_demo
      schema: public
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
  target: dev
